### ISSUE TITLE
Don't panic when querying virtual table

### ISSUE THREAD

**Issue by oxtoacart** [getlantern/zenodb#20]
We should just return an error like "can't query virtual table".

**Comment by oxtoacart** [comment]
Here's an example panic:

```
Apr 18 04:15:55 zeno-donyc1-031 zeno: DEBUG zenodb: cluster.go:686 Processed query in 189.308µs: select * from reduced group by app, period(8192 as h0m0s)
Apr 18 04:15:55 zeno-donyc1-031 zeno: panic: runtime error: invalid memory address or nil pointer dereference
Apr 18 04:15:55 zeno-donyc1-031 zeno: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x591566]
Apr 18 04:15:55 zeno-donyc1-031 zeno:
Apr 18 04:15:55 zeno-donyc1-031 zeno: goroutine 124 [running]:
Apr 18 04:15:55 zeno-donyc1-031 zeno: panic(0xa04580, 0xc420010030)
Apr 18 04:15:55 zeno-donyc1-031 zeno: #011/usr/local/go/src/runtime/panic.go:500 +0x1a1
Apr 18 04:15:55 zeno-donyc1-031 zeno: github.com/getlantern/zenodb.(*rowStore).iterate(0x0, 0xc423e8e000, 0x33, 0x33, 0x0, 0xc423bfd960, 0xc42010f508, 0xc4234c7a60)
Apr 18 04:15:55 zeno-donyc1-031 zeno: #011/Users/ox.to.a.cart/gocode/src/github.com/getlantern/zenodb/row_store.go:254 +0x26
Apr 18 04:15:55 zeno-donyc1-031 zeno: github.com/getlantern/zenodb.(*table).iterate(0xc420177800, 0xc423e8e000, 0x33, 0x33, 0x0, 0xc423bfd960, 0x0, 0xc420012000)
Apr 18 04:15:55 zeno-donyc1-031 zeno: #011/Users/ox.to.a.cart/gocode/src/github.com/getlantern/zenodb/table.go:302 +0x63
Apr 18 04:15:55 zeno-donyc1-031 zeno: github.com/getlantern/zenodb.(*queryable).Iterate(0xc423df2de0, 0xdbd4e0, 0xc423ac5ec0, 0xc423e709c0, 0xc423e709f0, 0x4129e9, 0xc4200463b8)
Apr 18 04:15:55 zeno-donyc1-031 zeno: #011/Users/ox.to.a.cart/gocode/src/github.com/getlantern/zenodb/query.go:109 +0x188
Apr 18 04:15:55 zeno-donyc1-031 zeno: github.com/getlantern/zenodb/core.(*group).Iterate(0xc423e7a1b0, 0xdbd4e0, 0xc423ac5ec0, 0xc423e76640, 0xc423e76660, 0x0, 0x0)
Apr 18 04:15:55 zeno-donyc1-031 zeno: #011/Users/ox.to.a.cart/gocode/src/github.com/getlantern/zenodb/core/group.go:202 +0x424
Apr 18 04:15:55 zeno-donyc1-031 zeno: github.com/getlantern/zenodb.(*DB).queryForRemote(0xc4201c6d10, 0xdbd4e0, 0xc423ac5ec0, 0xc423e7e6c0, 0x39, 0x9ac300, 0x0, 0x0, 0x0, 0xc423bfdd01, ...)
Apr 18 04:15:55 zeno-donyc1-031 zeno: #011/Users/ox.to.a.cart/gocode/src/github.com/getlantern/zenodb/cluster.go:689 +0x1ba
Apr 18 04:15:55 zeno-donyc1-031 zeno: github.com/getlantern/zenodb.(*DB).(github.com/getlantern/zenodb.queryForRemote)-fm(0xdbd4e0, 0xc423ac5ec0, 0xc423e7e6c0, 0x39, 0xc423ac5e00, 0x0, 0x0, 0x0, 0x1, 0xc423e76640, ...)
Apr 18 04:15:55 zeno-donyc1-031 zeno: #011/Users/ox.to.a.cart/gocode/src/github.com/getlantern/zenodb/zenodb.go:174 +0xcb
Apr 18 04:15:55 zeno-donyc1-031 zeno: github.com/getlantern/zenodb/rpc.(*client).ProcessRemoteQuery(0xc4201aa540, 0xdbd460, 0xc4200103d8, 0x1f, 0xc423731150, 0x0, 0x0, 0x0, 0x0, 0x0)
Apr 18 04:15:55 zeno-donyc1-031 zeno: #011/Users/ox.to.a.cart/gocode/src/github.com/getlantern/zenodb/rpc/rpc_client.go:207 +0x4b1
Apr 18 04:15:55 zeno-donyc1-031 zeno: main.main.func5.1(0x2faf080, 0xdbe500, 0xc4201aa540, 0x1f, 0xc423731150, 0x12a05f200)
Apr 18 04:15:55 zeno-donyc1-031 zeno: #011/Users/ox.to.a.cart/gocode/src/github.com/getlantern/zenodb/zeno/zeno.go:237 +0xea
Apr 18 04:15:55 zeno-donyc1-031 zeno: created by main.main.func5
Apr 18 04:15:55 zeno-donyc1-031 zeno: #011/Users/ox.to.a.cart/gocode/src/github.com/getlantern/zenodb/zeno/zeno.
```
