### ISSUE TITLE
Zeno follower stuck

### ISSUE THREAD

**Issue by oxtoacart** [getlantern/zenodb#64]
```
Aug 13 18:29:36 zeno-donyc1-007-001 zeno: goroutine 27671 [select, 8074 minutes]:
Aug 13 18:29:36 zeno-donyc1-007-001 zeno: github.com/getlantern/zenodb/vendor/google.golang.org/grpc.newClientStream.func4(0xc420296280, 0xc445a22380, 0xbd5a20, 0xc459ea9ef0)
Aug 13 18:29:36 zeno-donyc1-007-001 zeno: #011/Volumes/external/gocode/src/github.com/getlantern/zenodb/vendor/google.golang.org/grpc/stream.go:301 +0xfe
Aug 13 18:29:36 zeno-donyc1-007-001 zeno: created by github.com/getlantern/zenodb/vendor/google.golang.org/grpc.newClientStream
Aug 13 18:29:36 zeno-donyc1-007-001 zeno: #011/Volumes/external/gocode/src/github.com/getlantern/zenodb/vendor/google.golang.org/grpc/stream.go:300 +0xa4b
Aug 13 18:29:36 zeno-donyc1-007-001 zeno:
Aug 13 18:29:36 zeno-donyc1-007-001 zeno: goroutine 27690 [chan send, 8041 minutes]:
Aug 13 18:29:36 zeno-donyc1-007-001 zeno: github.com/getlantern/zenodb/rpc.(*client).ProcessRemoteQuery.func1(0xbd83e0, 0xc476906080, 0xc4339a9020, 0xc4339a8fc0)
Aug 13 18:29:36 zeno-donyc1-007-001 zeno: #011/Volumes/external/gocode/src/github.com/getlantern/zenodb/rpc/rpc_client.go:191 +0x91
Aug 13 18:29:36 zeno-donyc1-007-001 zeno: created by github.com/getlantern/zenodb/rpc.(*client).ProcessRemoteQuery
Aug 13 18:29:36 zeno-donyc1-007-001 zeno: #011/Volumes/external/gocode/src/github.com/getlantern/zenodb/rpc/rpc_client.go:185 +0x3a3
Aug 13 18:29:36 zeno-donyc1-007-001 zeno:
```

**Comment by myleshorton** [comment]
This one's done right @oxtoacart?

**Comment by oxtoacart** [comment]
No, not yet done.

**Comment by oxtoacart** [comment]
Haven't seen this specific problem in a while, closing.
