### ISSUE TITLE
Zeno panics when query doesn't select any real fields

### ISSUE THREAD

**Issue by oxtoacart** [getlantern/zenodb#65]
```
Aug 17 19:48:26 zeno-donyc1-072-001 zeno: ------------ Query Plan ------------
Aug 17 19:48:26 zeno-donyc1-072-001 zeno:
Aug 17 19:48:26 zeno-donyc1-072-001 zeno: select sum(unique_client) as client_count from (select 1 as unique_client from proxy_and_client ASOF '-1h' where app = 'lantern-client' and op = 'proxy' and geo_country = 'CN' and hostname(proxy_host) = proxy_name group by proxy_host, proxy_name, device_id, period(1 as h)) group by proxy_host, proxy_name
Aug 17 19:48:26 zeno-donyc1-072-001 zeno:
Aug 17 19:48:26 zeno-donyc1-072-001 zeno: <- flatten
Aug 17 19:48:26 zeno-donyc1-072-001 zeno:   <- group
Aug 17 19:48:26 zeno-donyc1-072-001 zeno:          by: [proxy_host (proxy_host) proxy_name (proxy_name)]
Aug 17 19:48:26 zeno-donyc1-072-001 zeno:          fields: sum(unique_client) as client_count
Aug 17 19:48:26 zeno-donyc1-072-001 zeno:     <- unflatten to sum(unique_client) as client_count
Aug 17 19:48:26 zeno-donyc1-072-001 zeno:       <- flatten
Aug 17 19:48:26 zeno-donyc1-072-001 zeno:         <- group
Aug 17 19:48:26 zeno-donyc1-072-001 zeno:                by: [device_id (device_id) proxy_host (proxy_host) proxy_name (proxy_name)]
Aug 17 19:48:26 zeno-donyc1-072-001 zeno:                fields: 1 as unique_client
Aug 17 19:48:26 zeno-donyc1-072-001 zeno:                as of: 2018-08-17 19:00:00 +0000 UTC
Aug 17 19:48:26 zeno-donyc1-072-001 zeno:           <- rowFilter where app = 'lantern-client' and op = 'proxy' and geo_country = 'CN' and hostname(proxy_host) = proxy_name
Aug 17 19:48:26 zeno-donyc1-072-001 zeno:             <- proxy_and_client
Aug 17 19:48:26 zeno-donyc1-072-001 zeno:
Aug 17 19:48:26 zeno-donyc1-072-001 zeno: ----------- End Query Plan ----------
Aug 17 19:48:29 zeno-donyc1-072-001 zeno: DEBUG zenodb: table.go:458 Coalescing 1 iterations on proxy_and_client
Aug 17 19:48:29 zeno-donyc1-072-001 zeno: DEBUG zenodb: row_store.go:650 Found filestore at zenodata/proxy_and_client/filestore_01534533267713047357_4.dat
Aug 17 19:48:29 zeno-donyc1-072-001 zeno: DEBUG zenodb: row_store.go:666 Set highWaterMark from data file: 2018-08-17 19:14:17.303324 +0000 UTC
Aug 17 19:48:29 zeno-donyc1-072-001 zeno: panic: runtime error: index out of range
Aug 17 19:48:29 zeno-donyc1-072-001 zeno:
Aug 17 19:48:29 zeno-donyc1-072-001 zeno: goroutine 108 [running]:
Aug 17 19:48:29 zeno-donyc1-072-001 zeno: github.com/getlantern/zenodb.(*DB).doProcessIterations.func2(0xc43a8d600a, 0xf0, 0xf20b, 0xc48039d500, 0x1f, 0x1f, 0x4413b7, 0x300, 0xb1fba0)
Aug 17 19:48:29 zeno-donyc1-072-001 zeno: #011/Volumes/external/gocode/src/github.com/getlantern/zenodb/table.go:472 +0x3dc
Aug 17 19:48:29 zeno-donyc1-072-001 zeno: github.com/getlantern/zenodb.(*rowStore).iterate.func1(0xc43a8d600a, 0xf0, 0xf20b, 0xc48039d500, 0x1f, 0x1f, 0x0, 0x0, 0x0, 0x12, ...)
Aug 17 19:48:29 zeno-donyc1-072-001 zeno: #011/Volumes/external/gocode/src/github.com/getlantern/zenodb/row_store.go:305 +0x80
Aug 17 19:48:29 zeno-donyc1-072-001 zeno: github.com/getlantern/zenodb.(*fileStore).iterate(0xc424681f80, 0xf82cd8, 0x1f, 0x1f, 0x0, 0xc4c1480000, 0xc4b27cfd88, 0xc49f6996e0, 0xc4200ba020, 0x0, ...)
Aug 17 19:48:29 zeno-donyc1-072-001 zeno: #011/Volumes/external/gocode/src/github.com/getlantern/zenodb/row_store.go:777 +0x1882
Aug 17 19:48:29 zeno-donyc1-072-001 zeno: github.com/getlantern/zenodb.(*rowStore).iterate(0xc4237c4500, 0xbd59e0, 0xc4c14802a0, 0xf82cd8, 0x0, 0x0, 0xc4c1480200, 0xc47c1c2030, 0xb4e694, 0x2, ...)
Aug 17 19:48:29 zeno-donyc1-072-001 zeno: #011/Volumes/external/gocode/src/github.com/getlantern/zenodb/row_store.go:304 +0x151
Aug 17 19:48:29 zeno-donyc1-072-001 zeno: github.com/getlantern/zenodb.(*DB).doProcessIterations(0xc420286680, 0xc4201dc580, 0x1, 0x1)
Aug 17 19:48:29 zeno-donyc1-072-001 zeno: #011/Volumes/external/gocode/src/github.com/getlantern/zenodb/table.go:496 +0x876
Aug 17 19:48:29 zeno-donyc1-072-001 zeno: github.com/getlantern/zenodb.(*DB).processIterations(0xc420286680)
Aug 17 19:48:29 zeno-donyc1-072-001 zeno: #011/Volumes/external/gocode/src/github.com/getlantern/zenodb/table.go:417 +0x82
Aug 17 19:48:29 zeno-donyc1-072-001 zeno: created by github.com/getlantern/zenodb.NewDB
Aug 17 19:48:29 zeno-donyc1-072-001 zeno: #011/Volumes/external/gocode/src/github.com/getlantern/zenodb/zenodb.go:261 +0x6e6
Aug 17 19:48:29 zeno-donyc1-072-001 kernel: [83818.939223] init: zeno main process ended, respawning
```

**Comment by oxtoacart** [comment]
This is deployed.
