### ISSUE TITLE
panic: runtime error: integer divide by zero

### ISSUE THREAD

**Issue by max-b** [getlantern/zenodb#86]
With the following schema:
```
replica:
  retentionperiod:  72h
  sql: >
    SELECT
      replica_view_bytes,
      replica_view_first_byte_ms,
      replica_view_response_time_ms,
      replica_view_response_rate_mbps,

      replica_upload_bytes,
      replica_upload_first_byte_ms,
      replica_upload_response_time_ms,
      replica_upload_response_rate_mbps

    FROM inbound

    WHERE op = 'replica_view' OR op = 'replica_upload'

    GROUP BY *
```
zeno panics with a divide by zero error when I attempt to query the replica table _only once there is data in the table_:

```
~/w/l/zenodb ❯❯❯ ../zenodb/zeno-cli -insecure -fresh
zeno-cli > select * from replica;
# time                                 _points    replica_view_bytes    replica_view_first_byte_ms    replica_view_response_time_ms    replica_view_response_rate_mbps    replica_upload_bytes    replica_upload_first_byte_ms    replica_upload_response_time_ms    replica_upload_response_rate_mbps
results age of 2329050h56m28.19708665s exceeds allowed age of 2h0m0s
zeno-cli > select * from replica;
# time                                 _points    replica_view_bytes    replica_view_first_byte_ms    replica_view_response_time_ms    replica_view_response_rate_mbps    replica_upload_bytes    replica_upload_first_byte_ms    replica_upload_response_time_ms    replica_upload_response_rate_mbps
zeno-cli > select * from replica;
rpc error: code = Unavailable desc = transport is closing
zeno-cli > select * from replica;
rpc error: code = Unavailable desc = transport is closing
```
Log from zeno:
```
DEBUG zenodb.web: handler.go:108 Starting 2 goroutines to process queries
DEBUG zenodb.follower.0.0: server.go:354 Serving HTTP
DEBUG zenodb.follower.0.0: server.go:364 Started
DEBUG zenodb.follower.0.0: zenodb.go:500 Memory InUse: 3.4 MB    Alloc: 2.3 MB    Sys: 74 MB     RSS: 21 MB
DEBUG zenodb.follower.0.0.replica: table.go:579 High Water Mark    disk: 1970-01-01 00:00:00 +0000 UTC    memory: 1970-01-01 00:00:00 +0000 UTC
DEBUG borda: http.go:126 Processed 0 measurements at 0 per second
DEBUG zenodb.follower.0.0: zenodb.go:500 Memory InUse: 2.8 MB    Alloc: 1.7 MB    Sys: 74 MB     RSS: 21 MB
DEBUG zenodb.rpc (0): rpc_server.go:264 No password specified, allowing access to world
DEBUG zenodb.follower.0.0: query.go:50 
------------ Query Plan ------------

select * from replica

<- flatten
  <- replica

----------- End Query Plan ----------
DEBUG zenodb.follower.0.0.replica: table.go:472 Coalescing 1 iterations
DEBUG zenodb.follower.0.0.replica: row_store.go:743 Iterating over 
DEBUG zenodb.follower.0.0.replica: row_store.go:766 No filestore available at , (yet), try reading the offset file
panic: runtime error: integer divide by zero

goroutine 45 [running]:
github.com/getlantern/zenodb/encoding.Sequence.ValueAtTime(0xc0001901e0, 0x11, 0x11, 0xf7c7f65, 0xed64b8554, 0x1226180, 0xd2d0e0, 0xc000182b10, 0x0, 0x73, ...)
	/home/maxb/go/pkg/mod/github.com/getlantern/zenodb@v0.0.0-20200504194452-62c132ac729a/encoding/seq.go:105 +0x2c8
github.com/getlantern/zenodb/core.(*flatten).Iterate.func2(0xc000312000, 0x94, 0x94, 0xc0001b4620, 0x9, 0x9, 0xd8, 0xc0001b4620, 0xc0005301e0)
	/home/maxb/go/pkg/mod/github.com/getlantern/zenodb@v0.0.0-20200504194452-62c132ac729a/core/flatten.go:69 +0x304
github.com/getlantern/zenodb.(*queryable).Iterate.func1(0xc000312000, 0x94, 0x94, 0xc0001b4620, 0x9, 0x9, 0xc00056f6a0, 0xa9d5dc9d, 0x6998bbc2f1bc7c0f)
	/home/maxb/go/pkg/mod/github.com/getlantern/zenodb@v0.0.0-20200504194452-62c132ac729a/query.go:141 +0xb4
github.com/getlantern/zenodb.(*table).iterate.func2(0xc000312000, 0x94, 0x94, 0xc0001b4620, 0x9, 0x9, 0xc0005b0560, 0x249249249249, 0x39)
	/home/maxb/go/pkg/mod/github.com/getlantern/zenodb@v0.0.0-20200504194452-62c132ac729a/table.go:378 +0x72
github.com/getlantern/zenodb.(*DB).doProcessIterations.func2(0xc000312000, 0x94, 0x94, 0xc0001b4540, 0x9, 0x9, 0xc000190300, 0x11, 0x11)
	/home/maxb/go/pkg/mod/github.com/getlantern/zenodb@v0.0.0-20200504194452-62c132ac729a/table.go:489 +0x1a3
github.com/getlantern/zenodb.(*rowStore).iterate.func2(0xc000312000, 0x94, 0x94, 0xc0001b4540, 0x9, 0x9, 0x0, 0x0, 0x0, 0x0, ...)
	/home/maxb/go/pkg/mod/github.com/getlantern/zenodb@v0.0.0-20200504194452-62c132ac729a/row_store.go:347 +0x83
github.com/getlantern/zenodb.(*fileStore).iterate.func1(0xc000312000, 0x94, 0x94, 0xc0001b4460, 0x9, 0x9, 0x0, 0x1, 0x17)
	/home/maxb/go/pkg/mod/github.com/getlantern/zenodb@v0.0.0-20200504194452-62c132ac729a/row_store.go:911 +0x163
github.com/getlantern/zenodb/bytetree.(*Tree).Walk(0xc00028c300, 0x160e0a2ce8a00c8e, 0xc00056fc08, 0xc0000780d0, 0x1)
	/home/maxb/go/pkg/mod/github.com/getlantern/zenodb@v0.0.0-20200504194452-62c132ac729a/bytetree/bytetree.go:94 +0x239
github.com/getlantern/zenodb.(*fileStore).iterate(0xc0000b4240, 0xc0001d8000, 0x9, 0x10, 0xc0005120f0, 0x540000, 0xc00056fce0, 0xc00050f100, 0xc0003a4140, 0xd4561bbda)
	/home/maxb/go/pkg/mod/github.com/getlantern/zenodb@v0.0.0-20200504194452-62c132ac729a/row_store.go:906 +0x1b67
github.com/getlantern/zenodb.(*rowStore).iterate(0xc0000b6380, 0xd24dc0, 0xc000620cc0, 0xc0001d8000, 0x9, 0x10, 0xc000620c01, 0xc00056fe68, 0x0, 0x0, ...)
	/home/maxb/go/pkg/mod/github.com/getlantern/zenodb@v0.0.0-20200504194452-62c132ac729a/row_store.go:346 +0x236
github.com/getlantern/zenodb.(*DB).doProcessIterations(0xc0000c2100, 0xc0003a6078, 0x1, 0x1)
	/home/maxb/go/pkg/mod/github.com/getlantern/zenodb@v0.0.0-20200504194452-62c132ac729a/table.go:510 +0x84d
github.com/getlantern/zenodb.(*DB).processIterations(0xc0000c2100)
	/home/maxb/go/pkg/mod/github.com/getlantern/zenodb@v0.0.0-20200504194452-62c132ac729a/table.go:431 +0x82
created by github.com/getlantern/zenodb.NewDB
	/home/maxb/go/pkg/mod/github.com/getlantern/zenodb@v0.0.0-20200504194452-62c132ac729a/zenodb.go:304 +0x71a
```

**Comment by oxtoacart** [comment]
The problem is that this schema doesn't specify a resolution for table `replica` and the database isn't catching this with any validation.

**Comment by max-b** [comment]
Great thanks for the help!!
